on:
  workflow_dispatch:
env:
  FREEZE: 1
  RELEASE_APR: "nguyenhoangnam123, test"

jobs:
  evaluate:
    runs-on: "ubuntu-latest"
    outputs:
      test: ${{steps.GetAPR.outputs.test}}
      apr: ${{steps.GetAPR.outputs.apr1}}
    steps:
      - name: apr
        id: GetAPR
        run: |
          echo "test"=`(echo hello)` >> $GITHUB_OUTPUT
          echo "apr1"=`(echo ${{env.RELEASE_APR}} | jq -R 'split(",")')` >> $GITHUB_OUTPUT
  run:
    needs: ["evaluate"]
    runs-on: "ubuntu-latest"
    if: contains(needs.evaluate.outputs.apr, github.actor)
    steps:
      - name: run
        run: echo "run"
  print_output:
    needs: ["evaluate"]
    runs-on: "ubuntu-latest"
    steps:
      - name: get-out
        id: Getout
        run: echo "123"
        env:
          OUT: ${{join(needs.evaluate.outputs.apr, '\n')}}
    
