on:
  workflow_dispatch:
env:
  FREEZE: 1
  RELEASE_APR: "nguyenhoangnam123, test"

jobs:
  evaluate:
    runs-on: "ubuntu-latest"
    outputs:
      apr: ${{steps.GetAPR.outputs.test}}
    steps:
      - name: apr
        id: GetAPR
        run: |
          echo "test=hello" >> $GITHUB_OUTPUT
  print_output:
    needs: ["evaluate"]
    runs-on: "ubuntu-latest"
    steps:
      - name: get-out
        id: Getout
        run: echo "123"
        env:
          OUT: ${{join(needs.evaluate.outputs.*, '\n')}}
    
